### ISSUE TITLE
Thoughts on syntax for beginners

### ISSUE THREAD

**Issue by chrisdavidmills** [dogwaddle/free-code-camp#37]
I've had a look at Your thoughts on syntax for beginners, and I agree that the MDN [split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) page is potentially more difficult than it could be. In the syntax listing:

<pre>str.split([separator[, limit]])</pre>

[, limit] basically means that the limit parameter is optional. In some of the newer documentation we've written, we would instead use this style: 

<pre>str.split(separator, limit)</pre>

And then put an "optional" label on the description of the limit parameter that follows. Would this better for beginners?

**Comment by dogwaddle** [comment]
```javascript
str.split(separator, limit) 
``` 
Yes that would be much better, the idea being that you are trying to get it to appear as close to how it would look "in the wild" as possible.

**Comment by chrisdavidmills** [comment]
I've passed this to Florian, our man who's in charge of the MDN JS section, to see what he thinks.
